### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by abernier**

### CODE REVIEW

**Comment by alexander-heimbuch** [comment]
Would be great to see this merged. @arnau are there any reasons not to have the latest sauce connect version running?

**Comment by arnau** [comment]
@alexander-heimbuch sorry I don't work at ustwo anymore. @daaain perhaps you could ping whomever looks after this?

**Comment by joscha** [comment]
any chance to get this merged @daaain?

**Comment by daaain** [comment]
I'm really sorry everyone to have made you wait this long, but asking around again in ustwo as it turns out no one is using Sauce Labs currently. Even our SL account is cancelled and read only now, so I can't even test these updates.

If any of you would be up for maintaining this please fork it and I'll put the link to your repo to the top of the README.

In any case, since we can't maintain it, we're going to archive the repo soon as leaving people hanging is the worst possible state for everyone.

**Comment by joscha** [comment]
I am happy to help maintain this @daaain

**Comment by daaain** [comment]
Thank you so much @joscha 🙏 

Please fork the repo and let us know the Github and Docker Hub URLs so we can add the links!

**Comment by joscha** [comment]
@daaain https://github.com/joscha/docker-sauce-connect and https://hub.docker.com/r/joscha/docker-sauce-connect/

**Comment by joscha** [comment]
Changes in this PR have been merged into https://github.com/joscha/docker-sauce-connect/commit/c1c6629ba54f59ebe8ff948e7a2cb780c24c7f8c

**Comment by daaain** [comment]
Perfect, I updated the README with the links and a notice: https://github.com/ustwo/docker-sauce-connect/commit/4bba2838195af549f7c590e5e56e332d3ac55855

**Pull request closed without merging**
